/** @type {import('tailwindcss').Config} */
module.exports = {
    content: [
        './app/**/*.{js,jsx,ts,tsx}',
        './components/**/*.{js,jsx,ts,tsx}',
    ],
    darkMode: 'class',
    theme: {
        extend: {
            colors: {
                'primary-container': '#1b4332',
                error: '#ba1a1a',
                'surface-variant': '#e4e2de',
                'surface-container-high': '#eae8e4',
                'on-tertiary-fixed': '#002114',
                'secondary-fixed-dim': '#e9c349',
                'on-tertiary-fixed-variant': '#0e5138',
                'on-secondary-fixed-variant': '#574500',
                'surface-container': '#efeeea',
                'surface-dim': '#dbdad6',
                background: '#fbf9f5',
                'primary-fixed': '#c1ecd4',
                'secondary-fixed': '#ffe088',
                primary: '#012d1d',
                'surface-bright': '#fbf9f5',
                'secondary-container': '#fed65b',
                'on-secondary-container': '#745c00',
                'surface-container-lowest': '#ffffff',
                outline: '#717973',
                'on-tertiary': '#ffffff',
                'primary-fixed-dim': '#a5d0b9',
                'on-primary-fixed': '#002114',
                'inverse-primary': '#a5d0b9',
                'inverse-on-surface': '#f2f0ed',
                secondary: '#735c00',
                'inverse-surface': '#30312e',
                'on-primary-container': '#86af99',
                'on-surface': '#1b1c1a',
                'on-primary': '#ffffff',
                'outline-variant': '#c1c8c2',
                'error-container': '#ffdad6',
                'on-error-container': '#93000a',
                surface: '#fbf9f5',
                'surface-container-low': '#f5f3ef',
                'tertiary-container': '#00452e',
                'on-background': '#1b1c1a',
                'surface-container-highest': '#e4e2de',
                'on-surface-variant': '#414844',
                'on-error': '#ffffff',
                'on-secondary': '#ffffff',
                'tertiary-fixed': '#b1f0ce',
                'tertiary-fixed-dim': '#95d4b3',
                tertiary: '#002d1c',
                'on-primary-fixed-variant': '#274e3d',
                'on-tertiary-container': '#75b393',
                'on-secondary-fixed': '#241a00',
                'surface-tint': '#3f6653',
            },
            borderRadius: {
                DEFAULT: '0.25rem',
                lg: '0.5rem',
                xl: '0.75rem',
                full: '9999px',
            },
            spacing: {
                gutter: '16px',
                'stack-lg': '48px',
                'stack-md': '24px',
                base: '8px',
                'stack-sm': '12px',
                'container-margin': '24px',
            },
            fontFamily: {
                'title-md': ['Hanken Grotesk'],
                'body-lg': ['Hanken Grotesk'],
                'body-md': ['Hanken Grotesk'],
                'headline-lg-mobile': ['Hanken Grotesk'],
                'data-mono': ['JetBrains Mono'],
                'display-lg': ['Hanken Grotesk'],
                'headline-lg': ['Hanken Grotesk'],
                'label-sm': ['Hanken Grotesk'],
            },
            fontSize: {
                'title-md': ['20px', { lineHeight: '28px', fontWeight: '600' }],
                'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
                'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
                'headline-lg-mobile': ['24px', { lineHeight: '32px', fontWeight: '700' }],
                'data-mono': ['16px', { lineHeight: '24px', letterSpacing: '0.02em', fontWeight: '500' }],
                'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '800' }],
                'headline-lg': ['32px', { lineHeight: '40px', fontWeight: '700' }],
                'label-sm': ['12px', { lineHeight: '16px', fontWeight: '700' }],
            },
        },
    },
    plugins: [require('@tailwindcss/forms'), require('@tailwindcss/container-queries')],
};